<?php

define('REG_EVENT_TAGS', 'Registration Event Tags');//Vocabulary
//define('EVENT_TAGS_ID', 5);


define('EVENT_STATION_TAGS', 'Event Station Tags');//Vocabulary
define('EVENT_STATION_TAGS_MACHINE_NAME', 'event_station_tags');

define('DEFAULT_EVENT', 'PTA Event'); //tjs 2011Dec13
define('DEFAULT_EVENT_STATION', 'PTA Event Station'); //tjs 2011Dec13
define('DEFAULT_EVENT_STATION_DESCRIPTION', 'This is a description of the PTA Event Station');
define('DEFAULT_SPOT_COUNT', 3);

//define('TAGS_ID', 1);
define('TAGS', 'Tags');//tjs 2013Nov29  //Default vocabulary
define('TAGS_MACHINE_NAME', 'Tags');//tjs 2013Nov29 



